spring:
  application:
    name: flow

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurances
    username: postgres
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      group-id: insuranceConsumer
      auto-offset-reset: earliest
      properties:
        "[spring.json.type.mapping]": eventData:com.demo.domain.entity.EventStoreEntity
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

server:
  port: 8082